[build]
publish = "public"
functions = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/admin"
to = "/admin-products.html"
status = 200

[[redirects]]
from = "/admin/products"
to = "/admin-products.html"
status = 200

[[redirects]]
from = "/admin/orders"
to = "/admin-orders.html"
status = 200

[[redirects]]
from = "/admin/users"
to = "/admin-users.html"
status = 200

[[redirects]]
from = "/admin/gallery"
to = "/admin-gallery.html"
status = 200

[[redirects]]
from = "/shop"
to = "/shop.html"
status = 200

[[redirects]]
from = "/cart"
to = "/cart.html"
status = 200

[[redirects]]
from = "/checkout"
to = "/checkout.html"
status = 200
